name: backend
on:
  push:
    branches:
    - main
    - master
    paths:
    - 'backend/**' # Spécifie le chemin vers le dossier backend
  pull_request:
    branches:
    - main
    - master
    paths:
    - 'backend/**' # Spécifie le chemin vers le dossier backend

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm i

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Deploy the solution
      run: echo "Deployment step"
